/* *****************************************
 * CSCI205 - Software Engineering and Design
 * Fall 2021
 *
 *
 * Name: Katy Martinson and Phil Morgan
 * Date: 10/4/2021
 * Time: 10:05 AM
 *
 * Project: csci205
 * Package: lab06
 * File: Employee
 * Description:
 * A very basic abstraction for an employee in a simple HR system
 * ****************************************
 */
package lab06;

import java.time.LocalDate;
import java.util.HashSet;

/**
 * A basic representation for an Employee to be stored in an HR database system
 *
 * @author Brian King
 */
public class Employee implements Payable {


    /**
     * A factory to generate unique IDs in a safe way
     */
    private static class IDFactory {

        /** Collection of unique Employee IDs generated / assigned */
        private static HashSet<Integer> setOfAssignedIDs = new HashSet<>();

        private static Integer generateID() {
            Integer newID = 1;
            while (setOfAssignedIDs.contains(newID)) {
                newID++;
            }
            return newID;
        }

        /**
         * checks if empID is already taken, if it is generates a new ID, if not
         * uses empId (called safeToUse in lab instructions)
         * @param empID an int that represents the employee ID
         * @return int, either one generated by generateID() or empID
         */
        private static int checkID(int empID) {;
            int x = setOfAssignedIDs.size();
            if (setOfAssignedIDs.contains(empID) || empID <= 0) {
                return generateID();
            }
            else {
                return empID;
            }
        }


    }

    /** Employee id */
    private int empID;

    /** First name */
    private String firstName;

    /** Last name */
    private String lastName;

    /** Social Security number */
    private int ssNum;

    /** Date employee was hired */
    private LocalDate hireDate;

    /** Current salary of the employee */
    private double salary;

    private final int WORK_HOURS = 2080;

    /**
     * Explicit constructor to create new employee
     *
     * @param empID     Employee id
     * @param firstName First name
     * @param lastName  Last name
     * @param ssNum     Social Security Number
     * @param hireDate  Hire date (as {@link LocalDate} object
     * @param salary    Current employee salary
     */
    public Employee(int empID, String firstName, String lastName, int ssNum, LocalDate hireDate, double salary) {
        this.empID = IDFactory.checkID(empID);
        IDFactory.setOfAssignedIDs.add(this.empID);
        this.firstName = firstName;
        this.lastName = lastName;
        this.ssNum = ssNum;
        this.hireDate = hireDate;
        this.salary = salary;
    }

    /**
     * @return the employee id
     */
    public int getEmpID() { return empID; }

    /**
     * @return employee first name
     */
    public String getFirstName() { return firstName; }

    /**
     * @return Last name
     */
    public String getLastName() { return lastName; }

    /**
     * @return Social Security number
     */
    public int getSsNum() {
        return ssNum;
    }

    /**
     * @return {@link LocalDate} employee was hired
     */
    public LocalDate getHireDate() {
        return hireDate;
    }

    /**
     * @return current employee salary
     */
    public double getSalary() {
        return salary;
    }

    /**
     * Change the name of the employee
     *
     * @param first - New first name
     * @param last - New last name
     */
    public void changeName(String first, String last) {
        this.firstName = first;
        this.lastName = last;
    }

    /**
     * Raise the salary by <code>salaryAdj</code> dollars.
     *
     * @param salaryAdj - amount to add to the current salary
     * @return the new salary
     */
    public double raiseSalary(double salaryAdj) {
        this.salary += salaryAdj;
        return this.salary;
    }

    /**
     * Return a string representation of the Employee
     *
     * @return the String of comma delimited values
     */
    @Override
    public String toString() {
        String s = this.empID + "," + this.lastName + "," + this.firstName;
        s += String.format(",%09d", this.ssNum);
        s += "," + HRDateUtils.dateToStr(this.hireDate);
        s += String.format(",%.2f", this.salary);
        return s;
    }

    /**
     * @param o the other Object to compare
     * @return True if this Employee has the same SS# as another employee
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Employee employee = (Employee) o;
        return ssNum == employee.ssNum;
    }

    @Override
    public double calculatePay(double numHrs) {
        double totalPay = 0;
        double hourlyRate = this.getSalary() / WORK_HOURS;
        if (numHrs > 40) {
            totalPay += (1.5 * hourlyRate) * (numHrs - 40);
            totalPay += hourlyRate * 40;
        }
        else {
            totalPay += hourlyRate * numHrs;
        }
        return totalPay;
    }

    @Override
    public String getPayTo() {
        return this.firstName + " " + this.lastName;
    }

    @Override
    public String getPayMemo() {
        return "Employee ID: " + this.getEmpID() + ", Pay Date: " + HRDateUtils.dateToStr(LocalDate.now());
    }
}

